/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiSettingsGetSettingsPhpGet200ResponseSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSettingsGetSettingsPhpGet200ResponseSettings{}

// ApiSettingsGetSettingsPhpGet200ResponseSettings struct for ApiSettingsGetSettingsPhpGet200ResponseSettings
type ApiSettingsGetSettingsPhpGet200ResponseSettings struct {
	DarkTheme         *int32                                                    `json:"dark_theme,omitempty"`
	MonthlyPrice      *int32                                                    `json:"monthly_price,omitempty"`
	ConvertCurrency   *int32                                                    `json:"convert_currency,omitempty"`
	RemoveBackground  *int32                                                    `json:"remove_background,omitempty"`
	ColorTheme        *string                                                   `json:"color_theme,omitempty"`
	HideDisabled      *int32                                                    `json:"hide_disabled,omitempty"`
	DisabledToBottom  *int32                                                    `json:"disabled_to_bottom,omitempty"`
	ShowOriginalPrice *int32                                                    `json:"show_original_price,omitempty"`
	MobileNav         *int32                                                    `json:"mobile_nav,omitempty"`
	CustomCss         *ApiSettingsGetSettingsPhpGet200ResponseSettingsCustomCss `json:"custom_css,omitempty"`
}

// NewApiSettingsGetSettingsPhpGet200ResponseSettings instantiates a new ApiSettingsGetSettingsPhpGet200ResponseSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSettingsGetSettingsPhpGet200ResponseSettings() *ApiSettingsGetSettingsPhpGet200ResponseSettings {
	this := ApiSettingsGetSettingsPhpGet200ResponseSettings{}
	return &this
}

// NewApiSettingsGetSettingsPhpGet200ResponseSettingsWithDefaults instantiates a new ApiSettingsGetSettingsPhpGet200ResponseSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSettingsGetSettingsPhpGet200ResponseSettingsWithDefaults() *ApiSettingsGetSettingsPhpGet200ResponseSettings {
	this := ApiSettingsGetSettingsPhpGet200ResponseSettings{}
	return &this
}

// GetDarkTheme returns the DarkTheme field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetDarkTheme() int32 {
	if o == nil || IsNil(o.DarkTheme) {
		var ret int32
		return ret
	}
	return *o.DarkTheme
}

// GetDarkThemeOk returns a tuple with the DarkTheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetDarkThemeOk() (*int32, bool) {
	if o == nil || IsNil(o.DarkTheme) {
		return nil, false
	}
	return o.DarkTheme, true
}

// HasDarkTheme returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasDarkTheme() bool {
	if o != nil && !IsNil(o.DarkTheme) {
		return true
	}

	return false
}

// SetDarkTheme gets a reference to the given int32 and assigns it to the DarkTheme field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetDarkTheme(v int32) {
	o.DarkTheme = &v
}

// GetMonthlyPrice returns the MonthlyPrice field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetMonthlyPrice() int32 {
	if o == nil || IsNil(o.MonthlyPrice) {
		var ret int32
		return ret
	}
	return *o.MonthlyPrice
}

// GetMonthlyPriceOk returns a tuple with the MonthlyPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetMonthlyPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.MonthlyPrice) {
		return nil, false
	}
	return o.MonthlyPrice, true
}

// HasMonthlyPrice returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasMonthlyPrice() bool {
	if o != nil && !IsNil(o.MonthlyPrice) {
		return true
	}

	return false
}

// SetMonthlyPrice gets a reference to the given int32 and assigns it to the MonthlyPrice field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetMonthlyPrice(v int32) {
	o.MonthlyPrice = &v
}

// GetConvertCurrency returns the ConvertCurrency field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetConvertCurrency() int32 {
	if o == nil || IsNil(o.ConvertCurrency) {
		var ret int32
		return ret
	}
	return *o.ConvertCurrency
}

// GetConvertCurrencyOk returns a tuple with the ConvertCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetConvertCurrencyOk() (*int32, bool) {
	if o == nil || IsNil(o.ConvertCurrency) {
		return nil, false
	}
	return o.ConvertCurrency, true
}

// HasConvertCurrency returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasConvertCurrency() bool {
	if o != nil && !IsNil(o.ConvertCurrency) {
		return true
	}

	return false
}

// SetConvertCurrency gets a reference to the given int32 and assigns it to the ConvertCurrency field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetConvertCurrency(v int32) {
	o.ConvertCurrency = &v
}

// GetRemoveBackground returns the RemoveBackground field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetRemoveBackground() int32 {
	if o == nil || IsNil(o.RemoveBackground) {
		var ret int32
		return ret
	}
	return *o.RemoveBackground
}

// GetRemoveBackgroundOk returns a tuple with the RemoveBackground field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetRemoveBackgroundOk() (*int32, bool) {
	if o == nil || IsNil(o.RemoveBackground) {
		return nil, false
	}
	return o.RemoveBackground, true
}

// HasRemoveBackground returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasRemoveBackground() bool {
	if o != nil && !IsNil(o.RemoveBackground) {
		return true
	}

	return false
}

// SetRemoveBackground gets a reference to the given int32 and assigns it to the RemoveBackground field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetRemoveBackground(v int32) {
	o.RemoveBackground = &v
}

// GetColorTheme returns the ColorTheme field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetColorTheme() string {
	if o == nil || IsNil(o.ColorTheme) {
		var ret string
		return ret
	}
	return *o.ColorTheme
}

// GetColorThemeOk returns a tuple with the ColorTheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetColorThemeOk() (*string, bool) {
	if o == nil || IsNil(o.ColorTheme) {
		return nil, false
	}
	return o.ColorTheme, true
}

// HasColorTheme returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasColorTheme() bool {
	if o != nil && !IsNil(o.ColorTheme) {
		return true
	}

	return false
}

// SetColorTheme gets a reference to the given string and assigns it to the ColorTheme field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetColorTheme(v string) {
	o.ColorTheme = &v
}

// GetHideDisabled returns the HideDisabled field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetHideDisabled() int32 {
	if o == nil || IsNil(o.HideDisabled) {
		var ret int32
		return ret
	}
	return *o.HideDisabled
}

// GetHideDisabledOk returns a tuple with the HideDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetHideDisabledOk() (*int32, bool) {
	if o == nil || IsNil(o.HideDisabled) {
		return nil, false
	}
	return o.HideDisabled, true
}

// HasHideDisabled returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasHideDisabled() bool {
	if o != nil && !IsNil(o.HideDisabled) {
		return true
	}

	return false
}

// SetHideDisabled gets a reference to the given int32 and assigns it to the HideDisabled field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetHideDisabled(v int32) {
	o.HideDisabled = &v
}

// GetDisabledToBottom returns the DisabledToBottom field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetDisabledToBottom() int32 {
	if o == nil || IsNil(o.DisabledToBottom) {
		var ret int32
		return ret
	}
	return *o.DisabledToBottom
}

// GetDisabledToBottomOk returns a tuple with the DisabledToBottom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetDisabledToBottomOk() (*int32, bool) {
	if o == nil || IsNil(o.DisabledToBottom) {
		return nil, false
	}
	return o.DisabledToBottom, true
}

// HasDisabledToBottom returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasDisabledToBottom() bool {
	if o != nil && !IsNil(o.DisabledToBottom) {
		return true
	}

	return false
}

// SetDisabledToBottom gets a reference to the given int32 and assigns it to the DisabledToBottom field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetDisabledToBottom(v int32) {
	o.DisabledToBottom = &v
}

// GetShowOriginalPrice returns the ShowOriginalPrice field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetShowOriginalPrice() int32 {
	if o == nil || IsNil(o.ShowOriginalPrice) {
		var ret int32
		return ret
	}
	return *o.ShowOriginalPrice
}

// GetShowOriginalPriceOk returns a tuple with the ShowOriginalPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetShowOriginalPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.ShowOriginalPrice) {
		return nil, false
	}
	return o.ShowOriginalPrice, true
}

// HasShowOriginalPrice returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasShowOriginalPrice() bool {
	if o != nil && !IsNil(o.ShowOriginalPrice) {
		return true
	}

	return false
}

// SetShowOriginalPrice gets a reference to the given int32 and assigns it to the ShowOriginalPrice field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetShowOriginalPrice(v int32) {
	o.ShowOriginalPrice = &v
}

// GetMobileNav returns the MobileNav field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetMobileNav() int32 {
	if o == nil || IsNil(o.MobileNav) {
		var ret int32
		return ret
	}
	return *o.MobileNav
}

// GetMobileNavOk returns a tuple with the MobileNav field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetMobileNavOk() (*int32, bool) {
	if o == nil || IsNil(o.MobileNav) {
		return nil, false
	}
	return o.MobileNav, true
}

// HasMobileNav returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasMobileNav() bool {
	if o != nil && !IsNil(o.MobileNav) {
		return true
	}

	return false
}

// SetMobileNav gets a reference to the given int32 and assigns it to the MobileNav field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetMobileNav(v int32) {
	o.MobileNav = &v
}

// GetCustomCss returns the CustomCss field value if set, zero value otherwise.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetCustomCss() ApiSettingsGetSettingsPhpGet200ResponseSettingsCustomCss {
	if o == nil || IsNil(o.CustomCss) {
		var ret ApiSettingsGetSettingsPhpGet200ResponseSettingsCustomCss
		return ret
	}
	return *o.CustomCss
}

// GetCustomCssOk returns a tuple with the CustomCss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) GetCustomCssOk() (*ApiSettingsGetSettingsPhpGet200ResponseSettingsCustomCss, bool) {
	if o == nil || IsNil(o.CustomCss) {
		return nil, false
	}
	return o.CustomCss, true
}

// HasCustomCss returns a boolean if a field has been set.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) HasCustomCss() bool {
	if o != nil && !IsNil(o.CustomCss) {
		return true
	}

	return false
}

// SetCustomCss gets a reference to the given ApiSettingsGetSettingsPhpGet200ResponseSettingsCustomCss and assigns it to the CustomCss field.
func (o *ApiSettingsGetSettingsPhpGet200ResponseSettings) SetCustomCss(v ApiSettingsGetSettingsPhpGet200ResponseSettingsCustomCss) {
	o.CustomCss = &v
}

func (o ApiSettingsGetSettingsPhpGet200ResponseSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSettingsGetSettingsPhpGet200ResponseSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DarkTheme) {
		toSerialize["dark_theme"] = o.DarkTheme
	}
	if !IsNil(o.MonthlyPrice) {
		toSerialize["monthly_price"] = o.MonthlyPrice
	}
	if !IsNil(o.ConvertCurrency) {
		toSerialize["convert_currency"] = o.ConvertCurrency
	}
	if !IsNil(o.RemoveBackground) {
		toSerialize["remove_background"] = o.RemoveBackground
	}
	if !IsNil(o.ColorTheme) {
		toSerialize["color_theme"] = o.ColorTheme
	}
	if !IsNil(o.HideDisabled) {
		toSerialize["hide_disabled"] = o.HideDisabled
	}
	if !IsNil(o.DisabledToBottom) {
		toSerialize["disabled_to_bottom"] = o.DisabledToBottom
	}
	if !IsNil(o.ShowOriginalPrice) {
		toSerialize["show_original_price"] = o.ShowOriginalPrice
	}
	if !IsNil(o.MobileNav) {
		toSerialize["mobile_nav"] = o.MobileNav
	}
	if !IsNil(o.CustomCss) {
		toSerialize["custom_css"] = o.CustomCss
	}
	return toSerialize, nil
}

type NullableApiSettingsGetSettingsPhpGet200ResponseSettings struct {
	value *ApiSettingsGetSettingsPhpGet200ResponseSettings
	isSet bool
}

func (v NullableApiSettingsGetSettingsPhpGet200ResponseSettings) Get() *ApiSettingsGetSettingsPhpGet200ResponseSettings {
	return v.value
}

func (v *NullableApiSettingsGetSettingsPhpGet200ResponseSettings) Set(val *ApiSettingsGetSettingsPhpGet200ResponseSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSettingsGetSettingsPhpGet200ResponseSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSettingsGetSettingsPhpGet200ResponseSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSettingsGetSettingsPhpGet200ResponseSettings(val *ApiSettingsGetSettingsPhpGet200ResponseSettings) *NullableApiSettingsGetSettingsPhpGet200ResponseSettings {
	return &NullableApiSettingsGetSettingsPhpGet200ResponseSettings{value: val, isSet: true}
}

func (v NullableApiSettingsGetSettingsPhpGet200ResponseSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSettingsGetSettingsPhpGet200ResponseSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
