/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiPaymentMethodsGetPaymentMethodsPhpGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiPaymentMethodsGetPaymentMethodsPhpGet200Response{}

// ApiPaymentMethodsGetPaymentMethodsPhpGet200Response struct for ApiPaymentMethodsGetPaymentMethodsPhpGet200Response
type ApiPaymentMethodsGetPaymentMethodsPhpGet200Response struct {
	Success *bool `json:"success,omitempty"`
	Title *string `json:"title,omitempty"`
	PaymentMethods []ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner `json:"payment_methods,omitempty"`
	Notes []string `json:"notes,omitempty"`
}

// NewApiPaymentMethodsGetPaymentMethodsPhpGet200Response instantiates a new ApiPaymentMethodsGetPaymentMethodsPhpGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiPaymentMethodsGetPaymentMethodsPhpGet200Response() *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response {
	this := ApiPaymentMethodsGetPaymentMethodsPhpGet200Response{}
	return &this
}

// NewApiPaymentMethodsGetPaymentMethodsPhpGet200ResponseWithDefaults instantiates a new ApiPaymentMethodsGetPaymentMethodsPhpGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiPaymentMethodsGetPaymentMethodsPhpGet200ResponseWithDefaults() *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response {
	this := ApiPaymentMethodsGetPaymentMethodsPhpGet200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) SetTitle(v string) {
	o.Title = &v
}

// GetPaymentMethods returns the PaymentMethods field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) GetPaymentMethods() []ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner {
	if o == nil || IsNil(o.PaymentMethods) {
		var ret []ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner
		return ret
	}
	return o.PaymentMethods
}

// GetPaymentMethodsOk returns a tuple with the PaymentMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) GetPaymentMethodsOk() ([]ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner, bool) {
	if o == nil || IsNil(o.PaymentMethods) {
		return nil, false
	}
	return o.PaymentMethods, true
}

// HasPaymentMethods returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) HasPaymentMethods() bool {
	if o != nil && !IsNil(o.PaymentMethods) {
		return true
	}

	return false
}

// SetPaymentMethods gets a reference to the given []ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner and assigns it to the PaymentMethods field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) SetPaymentMethods(v []ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) {
	o.PaymentMethods = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) GetNotes() []string {
	if o == nil || IsNil(o.Notes) {
		var ret []string
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) GetNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []string and assigns it to the Notes field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) SetNotes(v []string) {
	o.Notes = v
}

func (o ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.PaymentMethods) {
		toSerialize["payment_methods"] = o.PaymentMethods
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	return toSerialize, nil
}

type NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response struct {
	value *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response
	isSet bool
}

func (v NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response) Get() *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response {
	return v.value
}

func (v *NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response) Set(val *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response(val *ApiPaymentMethodsGetPaymentMethodsPhpGet200Response) *NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response {
	return &NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response{value: val, isSet: true}
}

func (v NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiPaymentMethodsGetPaymentMethodsPhpGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


