/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiSubscriptionsGetSubscriptionsPhpGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSubscriptionsGetSubscriptionsPhpGet200Response{}

// ApiSubscriptionsGetSubscriptionsPhpGet200Response struct for ApiSubscriptionsGetSubscriptionsPhpGet200Response
type ApiSubscriptionsGetSubscriptionsPhpGet200Response struct {
	// Whether the request was successful.
	Success *bool `json:"success,omitempty"`
	// The title of the response, typically 'subscriptions'.
	Title *string `json:"title,omitempty"`
	Subscriptions []ApiSubscriptionsGetSubscriptionsPhpGet200ResponseSubscriptionsInner `json:"subscriptions,omitempty"`
	// Warning messages or additional information.
	Notes []string `json:"notes,omitempty"`
}

// NewApiSubscriptionsGetSubscriptionsPhpGet200Response instantiates a new ApiSubscriptionsGetSubscriptionsPhpGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSubscriptionsGetSubscriptionsPhpGet200Response() *ApiSubscriptionsGetSubscriptionsPhpGet200Response {
	this := ApiSubscriptionsGetSubscriptionsPhpGet200Response{}
	return &this
}

// NewApiSubscriptionsGetSubscriptionsPhpGet200ResponseWithDefaults instantiates a new ApiSubscriptionsGetSubscriptionsPhpGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSubscriptionsGetSubscriptionsPhpGet200ResponseWithDefaults() *ApiSubscriptionsGetSubscriptionsPhpGet200Response {
	this := ApiSubscriptionsGetSubscriptionsPhpGet200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) SetTitle(v string) {
	o.Title = &v
}

// GetSubscriptions returns the Subscriptions field value if set, zero value otherwise.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) GetSubscriptions() []ApiSubscriptionsGetSubscriptionsPhpGet200ResponseSubscriptionsInner {
	if o == nil || IsNil(o.Subscriptions) {
		var ret []ApiSubscriptionsGetSubscriptionsPhpGet200ResponseSubscriptionsInner
		return ret
	}
	return o.Subscriptions
}

// GetSubscriptionsOk returns a tuple with the Subscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) GetSubscriptionsOk() ([]ApiSubscriptionsGetSubscriptionsPhpGet200ResponseSubscriptionsInner, bool) {
	if o == nil || IsNil(o.Subscriptions) {
		return nil, false
	}
	return o.Subscriptions, true
}

// HasSubscriptions returns a boolean if a field has been set.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) HasSubscriptions() bool {
	if o != nil && !IsNil(o.Subscriptions) {
		return true
	}

	return false
}

// SetSubscriptions gets a reference to the given []ApiSubscriptionsGetSubscriptionsPhpGet200ResponseSubscriptionsInner and assigns it to the Subscriptions field.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) SetSubscriptions(v []ApiSubscriptionsGetSubscriptionsPhpGet200ResponseSubscriptionsInner) {
	o.Subscriptions = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) GetNotes() []string {
	if o == nil || IsNil(o.Notes) {
		var ret []string
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) GetNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []string and assigns it to the Notes field.
func (o *ApiSubscriptionsGetSubscriptionsPhpGet200Response) SetNotes(v []string) {
	o.Notes = v
}

func (o ApiSubscriptionsGetSubscriptionsPhpGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSubscriptionsGetSubscriptionsPhpGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Subscriptions) {
		toSerialize["subscriptions"] = o.Subscriptions
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	return toSerialize, nil
}

type NullableApiSubscriptionsGetSubscriptionsPhpGet200Response struct {
	value *ApiSubscriptionsGetSubscriptionsPhpGet200Response
	isSet bool
}

func (v NullableApiSubscriptionsGetSubscriptionsPhpGet200Response) Get() *ApiSubscriptionsGetSubscriptionsPhpGet200Response {
	return v.value
}

func (v *NullableApiSubscriptionsGetSubscriptionsPhpGet200Response) Set(val *ApiSubscriptionsGetSubscriptionsPhpGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSubscriptionsGetSubscriptionsPhpGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSubscriptionsGetSubscriptionsPhpGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSubscriptionsGetSubscriptionsPhpGet200Response(val *ApiSubscriptionsGetSubscriptionsPhpGet200Response) *NullableApiSubscriptionsGetSubscriptionsPhpGet200Response {
	return &NullableApiSubscriptionsGetSubscriptionsPhpGet200Response{value: val, isSet: true}
}

func (v NullableApiSubscriptionsGetSubscriptionsPhpGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSubscriptionsGetSubscriptionsPhpGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


