/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAdminGetAdminSettingsPhpGet401Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAdminGetAdminSettingsPhpGet401Response{}

// ApiAdminGetAdminSettingsPhpGet401Response struct for ApiAdminGetAdminSettingsPhpGet401Response
type ApiAdminGetAdminSettingsPhpGet401Response struct {
	Success *bool    `json:"success,omitempty"`
	Title   *string  `json:"title,omitempty"`
	Notes   []string `json:"notes,omitempty"`
}

// NewApiAdminGetAdminSettingsPhpGet401Response instantiates a new ApiAdminGetAdminSettingsPhpGet401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAdminGetAdminSettingsPhpGet401Response() *ApiAdminGetAdminSettingsPhpGet401Response {
	this := ApiAdminGetAdminSettingsPhpGet401Response{}
	return &this
}

// NewApiAdminGetAdminSettingsPhpGet401ResponseWithDefaults instantiates a new ApiAdminGetAdminSettingsPhpGet401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAdminGetAdminSettingsPhpGet401ResponseWithDefaults() *ApiAdminGetAdminSettingsPhpGet401Response {
	this := ApiAdminGetAdminSettingsPhpGet401Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) SetTitle(v string) {
	o.Title = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) GetNotes() []string {
	if o == nil || IsNil(o.Notes) {
		var ret []string
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) GetNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []string and assigns it to the Notes field.
func (o *ApiAdminGetAdminSettingsPhpGet401Response) SetNotes(v []string) {
	o.Notes = v
}

func (o ApiAdminGetAdminSettingsPhpGet401Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAdminGetAdminSettingsPhpGet401Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	return toSerialize, nil
}

type NullableApiAdminGetAdminSettingsPhpGet401Response struct {
	value *ApiAdminGetAdminSettingsPhpGet401Response
	isSet bool
}

func (v NullableApiAdminGetAdminSettingsPhpGet401Response) Get() *ApiAdminGetAdminSettingsPhpGet401Response {
	return v.value
}

func (v *NullableApiAdminGetAdminSettingsPhpGet401Response) Set(val *ApiAdminGetAdminSettingsPhpGet401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAdminGetAdminSettingsPhpGet401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAdminGetAdminSettingsPhpGet401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAdminGetAdminSettingsPhpGet401Response(val *ApiAdminGetAdminSettingsPhpGet401Response) *NullableApiAdminGetAdminSettingsPhpGet401Response {
	return &NullableApiAdminGetAdminSettingsPhpGet401Response{value: val, isSet: true}
}

func (v NullableApiAdminGetAdminSettingsPhpGet401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAdminGetAdminSettingsPhpGet401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
