/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications{}

// ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications struct for ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications
type ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications struct {
	Enabled      *int32  `json:"enabled,omitempty"`
	SmtpAddress  *string `json:"smtp_address,omitempty"`
	SmtpPort     *int32  `json:"smtp_port,omitempty"`
	SmtpUsername *string `json:"smtp_username,omitempty"`
	SmtpPassword *string `json:"smtp_password,omitempty"`
	FromEmail    *string `json:"from_email,omitempty"`
	Encryption   *string `json:"encryption,omitempty"`
	OtherEmails  *string `json:"other_emails,omitempty"`
}

// NewApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications instantiates a new ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications() *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications {
	this := ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications{}
	return &this
}

// NewApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotificationsWithDefaults instantiates a new ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotificationsWithDefaults() *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications {
	this := ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetEnabled() int32 {
	if o == nil || IsNil(o.Enabled) {
		var ret int32
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetEnabledOk() (*int32, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given int32 and assigns it to the Enabled field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) SetEnabled(v int32) {
	o.Enabled = &v
}

// GetSmtpAddress returns the SmtpAddress field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetSmtpAddress() string {
	if o == nil || IsNil(o.SmtpAddress) {
		var ret string
		return ret
	}
	return *o.SmtpAddress
}

// GetSmtpAddressOk returns a tuple with the SmtpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetSmtpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.SmtpAddress) {
		return nil, false
	}
	return o.SmtpAddress, true
}

// HasSmtpAddress returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) HasSmtpAddress() bool {
	if o != nil && !IsNil(o.SmtpAddress) {
		return true
	}

	return false
}

// SetSmtpAddress gets a reference to the given string and assigns it to the SmtpAddress field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) SetSmtpAddress(v string) {
	o.SmtpAddress = &v
}

// GetSmtpPort returns the SmtpPort field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetSmtpPort() int32 {
	if o == nil || IsNil(o.SmtpPort) {
		var ret int32
		return ret
	}
	return *o.SmtpPort
}

// GetSmtpPortOk returns a tuple with the SmtpPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetSmtpPortOk() (*int32, bool) {
	if o == nil || IsNil(o.SmtpPort) {
		return nil, false
	}
	return o.SmtpPort, true
}

// HasSmtpPort returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) HasSmtpPort() bool {
	if o != nil && !IsNil(o.SmtpPort) {
		return true
	}

	return false
}

// SetSmtpPort gets a reference to the given int32 and assigns it to the SmtpPort field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) SetSmtpPort(v int32) {
	o.SmtpPort = &v
}

// GetSmtpUsername returns the SmtpUsername field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetSmtpUsername() string {
	if o == nil || IsNil(o.SmtpUsername) {
		var ret string
		return ret
	}
	return *o.SmtpUsername
}

// GetSmtpUsernameOk returns a tuple with the SmtpUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetSmtpUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.SmtpUsername) {
		return nil, false
	}
	return o.SmtpUsername, true
}

// HasSmtpUsername returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) HasSmtpUsername() bool {
	if o != nil && !IsNil(o.SmtpUsername) {
		return true
	}

	return false
}

// SetSmtpUsername gets a reference to the given string and assigns it to the SmtpUsername field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) SetSmtpUsername(v string) {
	o.SmtpUsername = &v
}

// GetSmtpPassword returns the SmtpPassword field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetSmtpPassword() string {
	if o == nil || IsNil(o.SmtpPassword) {
		var ret string
		return ret
	}
	return *o.SmtpPassword
}

// GetSmtpPasswordOk returns a tuple with the SmtpPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetSmtpPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.SmtpPassword) {
		return nil, false
	}
	return o.SmtpPassword, true
}

// HasSmtpPassword returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) HasSmtpPassword() bool {
	if o != nil && !IsNil(o.SmtpPassword) {
		return true
	}

	return false
}

// SetSmtpPassword gets a reference to the given string and assigns it to the SmtpPassword field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) SetSmtpPassword(v string) {
	o.SmtpPassword = &v
}

// GetFromEmail returns the FromEmail field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetFromEmail() string {
	if o == nil || IsNil(o.FromEmail) {
		var ret string
		return ret
	}
	return *o.FromEmail
}

// GetFromEmailOk returns a tuple with the FromEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetFromEmailOk() (*string, bool) {
	if o == nil || IsNil(o.FromEmail) {
		return nil, false
	}
	return o.FromEmail, true
}

// HasFromEmail returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) HasFromEmail() bool {
	if o != nil && !IsNil(o.FromEmail) {
		return true
	}

	return false
}

// SetFromEmail gets a reference to the given string and assigns it to the FromEmail field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) SetFromEmail(v string) {
	o.FromEmail = &v
}

// GetEncryption returns the Encryption field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetEncryption() string {
	if o == nil || IsNil(o.Encryption) {
		var ret string
		return ret
	}
	return *o.Encryption
}

// GetEncryptionOk returns a tuple with the Encryption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetEncryptionOk() (*string, bool) {
	if o == nil || IsNil(o.Encryption) {
		return nil, false
	}
	return o.Encryption, true
}

// HasEncryption returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) HasEncryption() bool {
	if o != nil && !IsNil(o.Encryption) {
		return true
	}

	return false
}

// SetEncryption gets a reference to the given string and assigns it to the Encryption field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) SetEncryption(v string) {
	o.Encryption = &v
}

// GetOtherEmails returns the OtherEmails field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetOtherEmails() string {
	if o == nil || IsNil(o.OtherEmails) {
		var ret string
		return ret
	}
	return *o.OtherEmails
}

// GetOtherEmailsOk returns a tuple with the OtherEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) GetOtherEmailsOk() (*string, bool) {
	if o == nil || IsNil(o.OtherEmails) {
		return nil, false
	}
	return o.OtherEmails, true
}

// HasOtherEmails returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) HasOtherEmails() bool {
	if o != nil && !IsNil(o.OtherEmails) {
		return true
	}

	return false
}

// SetOtherEmails gets a reference to the given string and assigns it to the OtherEmails field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) SetOtherEmails(v string) {
	o.OtherEmails = &v
}

func (o ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.SmtpAddress) {
		toSerialize["smtp_address"] = o.SmtpAddress
	}
	if !IsNil(o.SmtpPort) {
		toSerialize["smtp_port"] = o.SmtpPort
	}
	if !IsNil(o.SmtpUsername) {
		toSerialize["smtp_username"] = o.SmtpUsername
	}
	if !IsNil(o.SmtpPassword) {
		toSerialize["smtp_password"] = o.SmtpPassword
	}
	if !IsNil(o.FromEmail) {
		toSerialize["from_email"] = o.FromEmail
	}
	if !IsNil(o.Encryption) {
		toSerialize["encryption"] = o.Encryption
	}
	if !IsNil(o.OtherEmails) {
		toSerialize["other_emails"] = o.OtherEmails
	}
	return toSerialize, nil
}

type NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications struct {
	value *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications
	isSet bool
}

func (v NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) Get() *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications {
	return v.value
}

func (v *NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) Set(val *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) {
	v.value = val
	v.isSet = true
}

func (v NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) IsSet() bool {
	return v.isSet
}

func (v *NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications(val *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) *NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications {
	return &NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications{value: val, isSet: true}
}

func (v NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsEmailNotifications) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
