/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner{}

// ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner struct for ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner
type ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner struct {
	Id      *int32  `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Icon    *string `json:"icon,omitempty"`
	Enabled *int32  `json:"enabled,omitempty"`
	Order   *int32  `json:"order,omitempty"`
	InUse   *bool   `json:"in_use,omitempty"`
}

// NewApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner instantiates a new ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner() *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner {
	this := ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner{}
	return &this
}

// NewApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInnerWithDefaults instantiates a new ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInnerWithDefaults() *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner {
	this := ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) SetName(v string) {
	o.Name = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) SetIcon(v string) {
	o.Icon = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetEnabled() int32 {
	if o == nil || IsNil(o.Enabled) {
		var ret int32
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetEnabledOk() (*int32, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given int32 and assigns it to the Enabled field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) SetEnabled(v int32) {
	o.Enabled = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) SetOrder(v int32) {
	o.Order = &v
}

// GetInUse returns the InUse field value if set, zero value otherwise.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetInUse() bool {
	if o == nil || IsNil(o.InUse) {
		var ret bool
		return ret
	}
	return *o.InUse
}

// GetInUseOk returns a tuple with the InUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) GetInUseOk() (*bool, bool) {
	if o == nil || IsNil(o.InUse) {
		return nil, false
	}
	return o.InUse, true
}

// HasInUse returns a boolean if a field has been set.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) HasInUse() bool {
	if o != nil && !IsNil(o.InUse) {
		return true
	}

	return false
}

// SetInUse gets a reference to the given bool and assigns it to the InUse field.
func (o *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) SetInUse(v bool) {
	o.InUse = &v
}

func (o ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.InUse) {
		toSerialize["in_use"] = o.InUse
	}
	return toSerialize, nil
}

type NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner struct {
	value *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner
	isSet bool
}

func (v NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) Get() *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner {
	return v.value
}

func (v *NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) Set(val *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner(val *ApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) *NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner {
	return &NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner{value: val, isSet: true}
}

func (v NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiPaymentMethodsGetPaymentMethodsPhpGet200ResponsePaymentMethodsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
