/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications{}

// ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications struct for ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications
type ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications struct {
	Enabled *int32  `json:"enabled,omitempty"`
	Host    *string `json:"host,omitempty"`
	Topic   *string `json:"topic,omitempty"`
	Headers *string `json:"headers,omitempty"`
}

// NewApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications instantiates a new ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications() *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications {
	this := ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications{}
	return &this
}

// NewApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotificationsWithDefaults instantiates a new ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotificationsWithDefaults() *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications {
	this := ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) GetEnabled() int32 {
	if o == nil || IsNil(o.Enabled) {
		var ret int32
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) GetEnabledOk() (*int32, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given int32 and assigns it to the Enabled field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) SetEnabled(v int32) {
	o.Enabled = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) SetHost(v string) {
	o.Host = &v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) GetTopic() string {
	if o == nil || IsNil(o.Topic) {
		var ret string
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) GetTopicOk() (*string, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given string and assigns it to the Topic field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) SetTopic(v string) {
	o.Topic = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) GetHeaders() string {
	if o == nil || IsNil(o.Headers) {
		var ret string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) GetHeadersOk() (*string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given string and assigns it to the Headers field.
func (o *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) SetHeaders(v string) {
	o.Headers = &v
}

func (o ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	return toSerialize, nil
}

type NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications struct {
	value *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications
	isSet bool
}

func (v NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) Get() *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications {
	return v.value
}

func (v *NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) Set(val *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) {
	v.value = val
	v.isSet = true
}

func (v NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) IsSet() bool {
	return v.isSet
}

func (v *NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications(val *ApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) *NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications {
	return &NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications{value: val, isSet: true}
}

func (v NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiNotificationsGetNotificationSettingsPhpGet200ResponseNotificationSettingsNtfyNotifications) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
