/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiCategoriesGetCategoriesPhpGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCategoriesGetCategoriesPhpGet200Response{}

// ApiCategoriesGetCategoriesPhpGet200Response struct for ApiCategoriesGetCategoriesPhpGet200Response
type ApiCategoriesGetCategoriesPhpGet200Response struct {
	// Indicates whether the request was successful.
	Success *bool `json:"success,omitempty"`
	// The title of the response.
	Title *string `json:"title,omitempty"`
	Categories []ApiCategoriesGetCategoriesPhpGet200ResponseCategoriesInner `json:"categories,omitempty"`
	// Warning messages or additional information.
	Notes []string `json:"notes,omitempty"`
}

// NewApiCategoriesGetCategoriesPhpGet200Response instantiates a new ApiCategoriesGetCategoriesPhpGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCategoriesGetCategoriesPhpGet200Response() *ApiCategoriesGetCategoriesPhpGet200Response {
	this := ApiCategoriesGetCategoriesPhpGet200Response{}
	return &this
}

// NewApiCategoriesGetCategoriesPhpGet200ResponseWithDefaults instantiates a new ApiCategoriesGetCategoriesPhpGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCategoriesGetCategoriesPhpGet200ResponseWithDefaults() *ApiCategoriesGetCategoriesPhpGet200Response {
	this := ApiCategoriesGetCategoriesPhpGet200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) SetTitle(v string) {
	o.Title = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) GetCategories() []ApiCategoriesGetCategoriesPhpGet200ResponseCategoriesInner {
	if o == nil || IsNil(o.Categories) {
		var ret []ApiCategoriesGetCategoriesPhpGet200ResponseCategoriesInner
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) GetCategoriesOk() ([]ApiCategoriesGetCategoriesPhpGet200ResponseCategoriesInner, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []ApiCategoriesGetCategoriesPhpGet200ResponseCategoriesInner and assigns it to the Categories field.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) SetCategories(v []ApiCategoriesGetCategoriesPhpGet200ResponseCategoriesInner) {
	o.Categories = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) GetNotes() []string {
	if o == nil || IsNil(o.Notes) {
		var ret []string
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) GetNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []string and assigns it to the Notes field.
func (o *ApiCategoriesGetCategoriesPhpGet200Response) SetNotes(v []string) {
	o.Notes = v
}

func (o ApiCategoriesGetCategoriesPhpGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCategoriesGetCategoriesPhpGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	return toSerialize, nil
}

type NullableApiCategoriesGetCategoriesPhpGet200Response struct {
	value *ApiCategoriesGetCategoriesPhpGet200Response
	isSet bool
}

func (v NullableApiCategoriesGetCategoriesPhpGet200Response) Get() *ApiCategoriesGetCategoriesPhpGet200Response {
	return v.value
}

func (v *NullableApiCategoriesGetCategoriesPhpGet200Response) Set(val *ApiCategoriesGetCategoriesPhpGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCategoriesGetCategoriesPhpGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCategoriesGetCategoriesPhpGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCategoriesGetCategoriesPhpGet200Response(val *ApiCategoriesGetCategoriesPhpGet200Response) *NullableApiCategoriesGetCategoriesPhpGet200Response {
	return &NullableApiCategoriesGetCategoriesPhpGet200Response{value: val, isSet: true}
}

func (v NullableApiCategoriesGetCategoriesPhpGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCategoriesGetCategoriesPhpGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


