/*
Wallos API

API documentation for Wallos

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings{}

// ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings struct for ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings
type ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings struct {
	// Indicates if registrations are open (1 for true, 0 for false).
	RegistrationsOpen *int32 `json:"registrations_open,omitempty"`
	// The maximum number of users allowed.
	MaxUsers *int32 `json:"max_users,omitempty"`
	// Indicates if email verification is required (1 for true, 0 for false).
	RequireEmailVerification *int32 `json:"require_email_verification,omitempty"`
	// The server URL.
	ServerUrl *string `json:"server_url,omitempty"`
	// The SMTP address for sending emails.
	SmtpAddress *string `json:"smtp_address,omitempty"`
	// The port for the SMTP server.
	SmtpPort *int32 `json:"smtp_port,omitempty"`
	// The username for SMTP authentication.
	SmtpUsername *string `json:"smtp_username,omitempty"`
	// The password for SMTP authentication.
	SmtpPassword *string `json:"smtp_password,omitempty"`
	// The email address used as the sender.
	FromEmail *string `json:"from_email,omitempty"`
	// The encryption method for SMTP (e.g., tls, ssl).
	Encryption *string `json:"encryption,omitempty"`
	// Indicates if login is disabled (1 for true, 0 for false).
	LoginDisabled *int32 `json:"login_disabled,omitempty"`
	// The latest version of the application.
	LatestVersion *string `json:"latest_version,omitempty"`
	// Indicates if update notifications are enabled (1 for true, 0 for false).
	UpdateNotification *int32 `json:"update_notification,omitempty"`
}

// NewApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings instantiates a new ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings() *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings {
	this := ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings{}
	return &this
}

// NewApiAdminGetAdminSettingsPhpGet200ResponseAdminSettingsWithDefaults instantiates a new ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAdminGetAdminSettingsPhpGet200ResponseAdminSettingsWithDefaults() *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings {
	this := ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings{}
	return &this
}

// GetRegistrationsOpen returns the RegistrationsOpen field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetRegistrationsOpen() int32 {
	if o == nil || IsNil(o.RegistrationsOpen) {
		var ret int32
		return ret
	}
	return *o.RegistrationsOpen
}

// GetRegistrationsOpenOk returns a tuple with the RegistrationsOpen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetRegistrationsOpenOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistrationsOpen) {
		return nil, false
	}
	return o.RegistrationsOpen, true
}

// HasRegistrationsOpen returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasRegistrationsOpen() bool {
	if o != nil && !IsNil(o.RegistrationsOpen) {
		return true
	}

	return false
}

// SetRegistrationsOpen gets a reference to the given int32 and assigns it to the RegistrationsOpen field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetRegistrationsOpen(v int32) {
	o.RegistrationsOpen = &v
}

// GetMaxUsers returns the MaxUsers field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetMaxUsers() int32 {
	if o == nil || IsNil(o.MaxUsers) {
		var ret int32
		return ret
	}
	return *o.MaxUsers
}

// GetMaxUsersOk returns a tuple with the MaxUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetMaxUsersOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxUsers) {
		return nil, false
	}
	return o.MaxUsers, true
}

// HasMaxUsers returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasMaxUsers() bool {
	if o != nil && !IsNil(o.MaxUsers) {
		return true
	}

	return false
}

// SetMaxUsers gets a reference to the given int32 and assigns it to the MaxUsers field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetMaxUsers(v int32) {
	o.MaxUsers = &v
}

// GetRequireEmailVerification returns the RequireEmailVerification field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetRequireEmailVerification() int32 {
	if o == nil || IsNil(o.RequireEmailVerification) {
		var ret int32
		return ret
	}
	return *o.RequireEmailVerification
}

// GetRequireEmailVerificationOk returns a tuple with the RequireEmailVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetRequireEmailVerificationOk() (*int32, bool) {
	if o == nil || IsNil(o.RequireEmailVerification) {
		return nil, false
	}
	return o.RequireEmailVerification, true
}

// HasRequireEmailVerification returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasRequireEmailVerification() bool {
	if o != nil && !IsNil(o.RequireEmailVerification) {
		return true
	}

	return false
}

// SetRequireEmailVerification gets a reference to the given int32 and assigns it to the RequireEmailVerification field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetRequireEmailVerification(v int32) {
	o.RequireEmailVerification = &v
}

// GetServerUrl returns the ServerUrl field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetServerUrl() string {
	if o == nil || IsNil(o.ServerUrl) {
		var ret string
		return ret
	}
	return *o.ServerUrl
}

// GetServerUrlOk returns a tuple with the ServerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetServerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ServerUrl) {
		return nil, false
	}
	return o.ServerUrl, true
}

// HasServerUrl returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasServerUrl() bool {
	if o != nil && !IsNil(o.ServerUrl) {
		return true
	}

	return false
}

// SetServerUrl gets a reference to the given string and assigns it to the ServerUrl field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetServerUrl(v string) {
	o.ServerUrl = &v
}

// GetSmtpAddress returns the SmtpAddress field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetSmtpAddress() string {
	if o == nil || IsNil(o.SmtpAddress) {
		var ret string
		return ret
	}
	return *o.SmtpAddress
}

// GetSmtpAddressOk returns a tuple with the SmtpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetSmtpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.SmtpAddress) {
		return nil, false
	}
	return o.SmtpAddress, true
}

// HasSmtpAddress returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasSmtpAddress() bool {
	if o != nil && !IsNil(o.SmtpAddress) {
		return true
	}

	return false
}

// SetSmtpAddress gets a reference to the given string and assigns it to the SmtpAddress field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetSmtpAddress(v string) {
	o.SmtpAddress = &v
}

// GetSmtpPort returns the SmtpPort field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetSmtpPort() int32 {
	if o == nil || IsNil(o.SmtpPort) {
		var ret int32
		return ret
	}
	return *o.SmtpPort
}

// GetSmtpPortOk returns a tuple with the SmtpPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetSmtpPortOk() (*int32, bool) {
	if o == nil || IsNil(o.SmtpPort) {
		return nil, false
	}
	return o.SmtpPort, true
}

// HasSmtpPort returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasSmtpPort() bool {
	if o != nil && !IsNil(o.SmtpPort) {
		return true
	}

	return false
}

// SetSmtpPort gets a reference to the given int32 and assigns it to the SmtpPort field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetSmtpPort(v int32) {
	o.SmtpPort = &v
}

// GetSmtpUsername returns the SmtpUsername field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetSmtpUsername() string {
	if o == nil || IsNil(o.SmtpUsername) {
		var ret string
		return ret
	}
	return *o.SmtpUsername
}

// GetSmtpUsernameOk returns a tuple with the SmtpUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetSmtpUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.SmtpUsername) {
		return nil, false
	}
	return o.SmtpUsername, true
}

// HasSmtpUsername returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasSmtpUsername() bool {
	if o != nil && !IsNil(o.SmtpUsername) {
		return true
	}

	return false
}

// SetSmtpUsername gets a reference to the given string and assigns it to the SmtpUsername field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetSmtpUsername(v string) {
	o.SmtpUsername = &v
}

// GetSmtpPassword returns the SmtpPassword field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetSmtpPassword() string {
	if o == nil || IsNil(o.SmtpPassword) {
		var ret string
		return ret
	}
	return *o.SmtpPassword
}

// GetSmtpPasswordOk returns a tuple with the SmtpPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetSmtpPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.SmtpPassword) {
		return nil, false
	}
	return o.SmtpPassword, true
}

// HasSmtpPassword returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasSmtpPassword() bool {
	if o != nil && !IsNil(o.SmtpPassword) {
		return true
	}

	return false
}

// SetSmtpPassword gets a reference to the given string and assigns it to the SmtpPassword field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetSmtpPassword(v string) {
	o.SmtpPassword = &v
}

// GetFromEmail returns the FromEmail field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetFromEmail() string {
	if o == nil || IsNil(o.FromEmail) {
		var ret string
		return ret
	}
	return *o.FromEmail
}

// GetFromEmailOk returns a tuple with the FromEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetFromEmailOk() (*string, bool) {
	if o == nil || IsNil(o.FromEmail) {
		return nil, false
	}
	return o.FromEmail, true
}

// HasFromEmail returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasFromEmail() bool {
	if o != nil && !IsNil(o.FromEmail) {
		return true
	}

	return false
}

// SetFromEmail gets a reference to the given string and assigns it to the FromEmail field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetFromEmail(v string) {
	o.FromEmail = &v
}

// GetEncryption returns the Encryption field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetEncryption() string {
	if o == nil || IsNil(o.Encryption) {
		var ret string
		return ret
	}
	return *o.Encryption
}

// GetEncryptionOk returns a tuple with the Encryption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetEncryptionOk() (*string, bool) {
	if o == nil || IsNil(o.Encryption) {
		return nil, false
	}
	return o.Encryption, true
}

// HasEncryption returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasEncryption() bool {
	if o != nil && !IsNil(o.Encryption) {
		return true
	}

	return false
}

// SetEncryption gets a reference to the given string and assigns it to the Encryption field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetEncryption(v string) {
	o.Encryption = &v
}

// GetLoginDisabled returns the LoginDisabled field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetLoginDisabled() int32 {
	if o == nil || IsNil(o.LoginDisabled) {
		var ret int32
		return ret
	}
	return *o.LoginDisabled
}

// GetLoginDisabledOk returns a tuple with the LoginDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetLoginDisabledOk() (*int32, bool) {
	if o == nil || IsNil(o.LoginDisabled) {
		return nil, false
	}
	return o.LoginDisabled, true
}

// HasLoginDisabled returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasLoginDisabled() bool {
	if o != nil && !IsNil(o.LoginDisabled) {
		return true
	}

	return false
}

// SetLoginDisabled gets a reference to the given int32 and assigns it to the LoginDisabled field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetLoginDisabled(v int32) {
	o.LoginDisabled = &v
}

// GetLatestVersion returns the LatestVersion field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetLatestVersion() string {
	if o == nil || IsNil(o.LatestVersion) {
		var ret string
		return ret
	}
	return *o.LatestVersion
}

// GetLatestVersionOk returns a tuple with the LatestVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetLatestVersionOk() (*string, bool) {
	if o == nil || IsNil(o.LatestVersion) {
		return nil, false
	}
	return o.LatestVersion, true
}

// HasLatestVersion returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasLatestVersion() bool {
	if o != nil && !IsNil(o.LatestVersion) {
		return true
	}

	return false
}

// SetLatestVersion gets a reference to the given string and assigns it to the LatestVersion field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetLatestVersion(v string) {
	o.LatestVersion = &v
}

// GetUpdateNotification returns the UpdateNotification field value if set, zero value otherwise.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetUpdateNotification() int32 {
	if o == nil || IsNil(o.UpdateNotification) {
		var ret int32
		return ret
	}
	return *o.UpdateNotification
}

// GetUpdateNotificationOk returns a tuple with the UpdateNotification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) GetUpdateNotificationOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdateNotification) {
		return nil, false
	}
	return o.UpdateNotification, true
}

// HasUpdateNotification returns a boolean if a field has been set.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) HasUpdateNotification() bool {
	if o != nil && !IsNil(o.UpdateNotification) {
		return true
	}

	return false
}

// SetUpdateNotification gets a reference to the given int32 and assigns it to the UpdateNotification field.
func (o *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) SetUpdateNotification(v int32) {
	o.UpdateNotification = &v
}

func (o ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RegistrationsOpen) {
		toSerialize["registrations_open"] = o.RegistrationsOpen
	}
	if !IsNil(o.MaxUsers) {
		toSerialize["max_users"] = o.MaxUsers
	}
	if !IsNil(o.RequireEmailVerification) {
		toSerialize["require_email_verification"] = o.RequireEmailVerification
	}
	if !IsNil(o.ServerUrl) {
		toSerialize["server_url"] = o.ServerUrl
	}
	if !IsNil(o.SmtpAddress) {
		toSerialize["smtp_address"] = o.SmtpAddress
	}
	if !IsNil(o.SmtpPort) {
		toSerialize["smtp_port"] = o.SmtpPort
	}
	if !IsNil(o.SmtpUsername) {
		toSerialize["smtp_username"] = o.SmtpUsername
	}
	if !IsNil(o.SmtpPassword) {
		toSerialize["smtp_password"] = o.SmtpPassword
	}
	if !IsNil(o.FromEmail) {
		toSerialize["from_email"] = o.FromEmail
	}
	if !IsNil(o.Encryption) {
		toSerialize["encryption"] = o.Encryption
	}
	if !IsNil(o.LoginDisabled) {
		toSerialize["login_disabled"] = o.LoginDisabled
	}
	if !IsNil(o.LatestVersion) {
		toSerialize["latest_version"] = o.LatestVersion
	}
	if !IsNil(o.UpdateNotification) {
		toSerialize["update_notification"] = o.UpdateNotification
	}
	return toSerialize, nil
}

type NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings struct {
	value *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings
	isSet bool
}

func (v NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) Get() *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings {
	return v.value
}

func (v *NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) Set(val *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings(val *ApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) *NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings {
	return &NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings{value: val, isSet: true}
}

func (v NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAdminGetAdminSettingsPhpGet200ResponseAdminSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
